apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: paf
spec:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  minReplicas: 4
  maxReplicas: 7
  {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
  minReplicas: 1
  maxReplicas: 1
  {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
  minReplicas: 1
  maxReplicas: 2
  {{ else }}
  # The branch environment takes up a lot of resources so the number of pods has been kept low
  minReplicas: 1
  maxReplicas: 1
  {{ end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: {{ .APP_NAME }}
    {{ end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 256Mi
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 100
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 35
