---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: redis-data-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: redis-data
  {{ end }}
spec:
  accessModes:
    - {{ .REDIS_PERSISTENCE_ACCESS_MODES }}
  resources:
    requests:
      storage: {{ .REDIS_PERSISTENCE_SIZE }}
  {{ if .REDIS_PERSISTENCE_STORAGE_CLASS }}
  storageClassName: {{ .REDIS_PERSISTENCE_STORAGE_CLASS }}
  {{ end }}
