const anotherPerson = new Array();

module.exports = {
  'csrf-secret': '6erVCDutWgtcGyWPc2da5WGp',
  errors: null,
  'crime-type': 'immigration-crime',
  'immigration-crime-group': 'immigration-crime-fake-marriage',
  'smuggling-crime-group': '',
  steps: [
    '/crime-type',
    '/crime-children',
    '/when-crime-happened',
    '/crime-transport',
    '/crime-delivery',
    '/crime-location',
    '/report-person',
    '/report-person-name',
    '/report-person-dob',
    '/report-person-age-range',
    '/report-person-nationality',
    '/report-person-place-of-birth',
    '/report-person-gender',
    '/report-person-id',
    '/report-person-location',
    '/report-person-occupation',
    '/report-person-study',
    '/report-person-transport',
    '/report-person-description',
    '/has-additionalPerson',
    '/add-person',
    '/add-person-dob',
    '/add-person-age',
    '/add-person-nationality',
    '/add-person-gender',
    '/add-person-identity',
    '/person-details',
    '/report-organisation',
    '/other-info-description',
    '/other-info-another-crime',
    '/other-info-file-upload',
    '/add-other-info-file-upload',
    '/about-you',
    '/does-anyone-else-know',
    '/have-you-reported-before',
    '/how-do-you-know-the-person',
    '/can-use-info-without-risk',
    '/about-you-details',
    '/about-you-dob',
    '/about-you-nationality',
    '/about-you-gender',
    '/about-you-contact',
    '/confirm'
  ],
  'crime-children': 'crime-childen-unknown',
  'when-crime-happened': 'dont-know-when-it-happend',
  'happening-now-info': '',
  'ongoing-info': '',
  'already-happened-info': '',
  'report-person': 'yes',
  persons: { anotherPerson, aggregatedValues: [ [Object], [Object], [Object] ] },
  'additional-people-table': [
    'Person Added IS =personAddFirstName:testb, personAddFamilyName:test',
    'Person Added IS =personAddFirstName:testc',
    'Person Added IS =personAddFirstName:testd, personAddFamilyName:test, '
    + 'personAddNickname:test, personAddDob:1985-02-01, personAddAgeRange:35-44, '
    + 'personAddNationality:Nationality-India, personAddGender:male'
  ],
  'crime-transport': 'unknown',
  'transport-group': '',
  'crime-delivery': 'unknown',
  'freight-more-info': '',
  'express-more-info': '',
  'post-more-info': '',
  'crime-location': 'no',
  'crime-location-country': '',
  'crime-location-address-line1': '',
  'crime-location-address-line2': '',
  'crime-location-address-town': '',
  'crime-location-address-county': '',
  'crime-location-address-postcode': '',
  'crime-location-phone': '',
  'report-organisation': 'unknown',
  'other-info-description': '',
  'other-info-another-crime': 'no',
  'other-info-another-crime-description': '',
  'how-did-you-find-out-about-the-crime': '',
  'does-anyone-else-know': '',
  'have-you-reported-before': '',
  'how-do-you-know-the-person': '',
  'can-use-info-without-risk': 'no',
  'about-you-first-name': 'testa',
  'about-you-family-name': 'testaa',
  'about-you-dob': '1981-01-01',
  'about-you-nationality': '',
  'about-you-gender': 'male',
  'about-you-contact': 'no',
  'report-person-first-name': 'testb',
  'report-person-family-name': 'testb',
  'report-person-nickname': 'test',
  'report-person-dob': '1982-02-01',
  'report-person-age-range': '35-44',
  'report-person-nationality': 'Nationality-India',
  'report-person-place-of-birth': 'delhi',
  'report-person-gender': 'male',
  'report-person-passport': '',
  'report-person-id': '',
  'report-person-ni': '',
  'report-person-location': 'location-unknown',
  'report-person-occupation': 'unknown',
  'report-person-study': 'unknown',
  'report-person-transport': 'unknown',
  'report-person-description': '',
  hasAdditionalPerson: 'yes',
  images: [
    {
      name: 'EUDA v10 master.pdf',
      mimetype: 'application/pdf',
      id: '1cbcb095-b4b8-43ef-be12-2490634889b3',
      url: 'http://s3.com/foo/0.6035454156299347'
    }
  ],
  'other-info-file-uploads': [
    {
      id: '10eff1a0-8930-11ee-9f9e-d53eb368a8f8',
      'info-file-upload': 'EUDA v10 master.pdf',
      record: 'EUDA v10 master.pdf'
    }
  ],
  'other-info-file-uploads-saved': true,
  'other-info-file-uploads-add-another': 'no'
};
