---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  name: ims-resolver
  {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: ims-resolver-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  annotations:
    downscaler/uptime: {{ .NON_PROD_AVAILABILITY }}
  name: ims-resolver
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: ims-resolver-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: ims-resolver
      {{ end }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/"
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        name: ims-resolver-{{ .DRONE_SOURCE_BRANCH }}
        service: ims-resolver-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        name: ims-resolver
        service: ims-resolver
        {{ end }}
    spec:
      containers:
        - name: ims-resolver
          image: quay.io/ukhomeofficedigital/ims-resolver:435e8996942c45a5545cb639918f30d8586b6400
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: {{ .APP_NAME }}-configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: {{ .APP_NAME }}-configmap
                {{ end }}
            - configMapRef:
                name: imscertchain-store
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/etc/ssl/certs/ims-prp1-ca.crt"
            - name: TZ
              value: Europe/London
            - name: IMS_API_USER
              valueFrom:
                secretKeyRef:
                  name: ims-credentials
                  key: ims_user
            - name: IMS_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ims-credentials
                  key: ims_password

            - name: WSDL
              valueFrom:
                secretKeyRef:
                  name: ims-credentials
                  key: ims_wsdl
            - name: IMS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ims-credentials
                  key: ims_endpoint
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: secret
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: id
            - name: KEYCLOAK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-user
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-user
                  key: password
            {{ if (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
            - name: SQS_URL
              valueFrom:
                secretKeyRef:
                  name: sas-paf-branch-sqs-queue
                  key: sqs_url
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sas-paf-branch-sqs-queue
                  key: access_key_id
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sas-paf-branch-sqs-queue
                  key: secret_access_key
            {{ else if (eq .KUBE_NAMESPACE .UAT_ENV) }}
            - name: SQS_URL
              valueFrom:
                secretKeyRef:
                  name: sas-paf-uat-sqs-queue
                  key: sqs_url
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sas-paf-uat-sqs-queue
                  key: access_key_id
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sas-paf-uat-sqs-queue
                  key: secret_access_key
            {{ else if (eq .KUBE_NAMESPACE .PROD_ENV) }}
            - name: SQS_URL
              valueFrom:
                secretKeyRef:
                  name: sas-paf-sqs-queue
                  key: sqs_url
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sas-paf-sqs-queue
                  key: access_key_id
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sas-paf-sqs-queue
                  key: secret_access_key
            {{ end }}
          securityContext:
            runAsNonRoot: true
          resources:
            {{ if or (eq .KUBE_NAMESPACE .BRANCH_ENV) (eq .KUBE_NAMESPACE .UAT_ENV) (eq .KUBE_NAMESPACE .STG_ENV) }}
            limits:
              memory: 256Mi
              cpu: 300m
            requests:
              memory: 10Mi
              cpu: 10m
            {{ else }}
            limits:
              memory: 1024Mi
              cpu: 300m
            requests:
              memory: 512Mi
              cpu: 10m  
            {{ end }}          
          volumeMounts:
            - name: imscertchain-store
              mountPath: /etc/ssl/certs/ims-prp1-ca.crt
              subPath: ims-prp1-ca.crt
              readOnly: false
      volumes:
        - name: imscertchain-store
          configMap:
            name: imscertchain-store
